services:
  app:
    image: php:8.1-fpm
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel_network

  webserver:
    image: nginx:latest
    container_name: laravel_webserver
    volumes:
      - .:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel_network

  database:
    image: mysql:8.0
    container_name: laravel_database
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - laravel_network

volumes:
  dbdata:

networks:
  laravel_network:
    driver: bridge
